if [ "$(ls -A ~/google-drive-phenikaa)" ]; then
    echo "~/google-drive-phenikaa is already mounted."
else
    echo "~/google-drive-phenikaa has been mounted."
    google-drive-ocamlfuse ~/google-drive-phenikaa/
fi
